
import './vuejs/main'
import './dependences/axios'
import './components/jquery'
import './components/customSelect'
import './components/carousel'
import './components/cookie'
import './components/followDot'
import './components/header'
import './components/footer'
import './components/abstraction'
import './components/locomotive'
import './components/magnetic'
import './components/scrolltrigger'
